scripts/update_apt: now it's fatal if we cannot update the pkgs
It was not fatal earlier, when update_apt was part of the main Neubot
repo, because I used to make Neubot releases from many systems.

Now that the script is in a Debian-only repo, it's more robust to abort
if we cannot update the pkgs.

diff --git a/scripts/update_apt b/scripts/update_apt
--- a/scripts/update_apt
+++ b/scripts/update_apt
@@ -44,5 +44,6 @@ if [ -x /usr/bin/dpkg-scanpackages ]; then
     }
     test $? || exit 1
 else
-    echo "warning: could not update apt: dpkg-scanpackages not available" 1>&2
+    echo "FATAL: could not update apt: dpkg-scanpackages not available" 1>&2
+    exit 1
 fi
